/**
 * Created by Wayuki on 2017-07-03.
 */
export const LOBBY_ACTIONS = {
  ADD_ROOM: 'ADD_ROOM_TO_LOBBY_PAGE',
};

export const CHESS_GAME_ACTIONS = {
  REGISTER_MOVES: 'REGISTER_MOVES_TO_CHESS_GAME_PAGE',
  RESET_MOVES: 'RESET_MOVES_ON_CHESS_GAME_PAGE',
  SWITCH_TURN: 'SWITCH_TURN_ON_CHESS_GAME_PAGE',
  REGISTER_VICTORY: 'REGISTER_VICTORY_ON_CHESS_GAME_PAGE',
  REGISTER_CHESS_PIECES: 'REGISTER_CHESS_PIECES_TO_CHESS_GAME_PAGE',
};

export const ROOM_ACTIONS = {
  TOGGLE_PLAYER2_READY: 'TOGGLE_PLAYER2_READY',
  PLAYER2_JOIN: 'PLAYER2_JOIN_TO_ROOM',
  PLAYER2_LEAVE: 'PLAYER2_LEAVE_ROOM',
};
export default 'ACTION_TYPES';
