/**
 * Created by Wayuki on 2017-07-03.
 */
export const LOBBY_ACTIONS = {
  ADD_ROOM: 'ADD_ROOM_TO_LOBBY_PAGE',
};

export const ROOM_ACTIONS = {
  TOGGLE_PLAYER2_READY: 'TOGGLE_PLAYER2_READY',
  PLAYER2_JOIN: 'PLAYER2_JOIN_TO_ROOM',
  PLAYER2_LEAVE: 'PLAYER2_LEAVE_ROOM',
};
export default 'ACTION_TYPES';
