/**
 * Created by Wayuki on 2017-07-03.
 */
export const AUTH_ACTIONS = {
  REGISTER_USER: 'REGISTER_USER_TO_APPLICATION',
};

export const LOGIN_ACTIONS = {
  HANDLE_LOGIN_FIELD_CHANGE: 'HANDLE_LOGIN_FORM_FIELDS_CHANGE',
  REGISTER_ERRORS: 'REGISTER_LOGIN_FORM_FIELDS_ERRORS',
};

export const LOBBY_ACTIONS = {
  ADD_ROOM: 'ADD_ROOM_TO_LOBBY_PAGE',
  TOGGLE_ROOM_CREATION: 'TOGGLE_LOBBY_ROOM_ROOM_CREATION',
  HANDLE_FORM_FIELD_CHANGE: 'HANDLE_LOBBY_CREATE_ROOM_FORM_FIELD_CHANGE',
};

export const CHESS_GAME_ACTIONS = {
  REGISTER_MOVES: 'REGISTER_MOVES_TO_CHESS_GAME_PAGE',
  RESET_MOVES: 'RESET_MOVES_ON_CHESS_GAME_PAGE',
  SWITCH_TURN: 'SWITCH_TURN_ON_CHESS_GAME_PAGE',
  REGISTER_VICTORY: 'REGISTER_VICTORY_ON_CHESS_GAME_PAGE',
  REGISTER_CHESS_PIECES: 'REGISTER_CHESS_PIECES_TO_CHESS_GAME_PAGE',
  REGISTER_PLAYERS: 'REGISTER_PLAYERS_TO_CHESS_GAME_PAGE',
  TOGGLE_LEAVING: 'TOGGLE_LEAVING_CHESS_GAME_PAGE',
  RESET_STATE: 'RESET_CHESS_GAME_PAGE_STATE',
  STATE_LOADED: 'CHESS_GAME_PAGE_STATE_LOADED',
};

export const ROOM_ACTIONS = {
  TOGGLE_PLAYER2_READY: 'TOGGLE_PLAYER2_READY',
  PLAYER2_JOIN: 'PLAYER2_JOIN_TO_ROOM',
  PLAYER2_LEAVE: 'PLAYER2_LEAVE_ROOM',
};
export default 'ACTION_TYPES';
